In [40]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
data = pd.read_csv("data/insurance_data.csv")
data.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [42]:
x = data.drop("bought_insurance" , axis =1)
y = data["bought_insurance"]

In [15]:
import sklearn

In [16]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_tain , y_test = train_test_split(x , y, test_size=0.2 , random_state=42)

In [17]:
len(x_train)

22

In [18]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,) , activation = "sigmoid" , kernel_initializer="ones" , bias_initializer="zeros")
])

/Users/saianand/Projects/deep-learning-intro/env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.compile(optimizer="adam" , loss = "binary_crossentropy" , metrics = ["accuracy"])

In [ ]:
model.fit(x_train , y_tain , epochs = 5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.5000 - loss: 15.4545
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 15.4386
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 15.4226
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 15.4067
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 15.3907
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 15.3748
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 15.3588
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5000 - loss: 15.3429
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 15.3269
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 15.3110
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 15.2950
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy

In [43]:
model.evaluate(x_test , y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.2536


[0.2536366879940033, 1.0]

In [45]:
model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[0.84977895],
       [0.7850946 ],
       [0.85758007],
       [0.2389358 ],
       [0.3310796 ],
       [0.25047943]], dtype=float32)

In [46]:
y_test

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

# Lets see w1 and w2 and bias in gradient descent curve


In [48]:
coeff , intercept = model.get_weights()

In [49]:
coeff , intercept

(array([[0.06246601],
        [0.7050808 ]], dtype=float32),
 array([-2.7826393], dtype=float32))

# lets implement this whole thing using RAW python which we did using keras and tensorflow

In [51]:
def sigmoid(x):
    import math
    return 1/(1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [52]:
def prediction_fucntion(age , affordibility):
    weighted_sum = coeff[0]*age + coeff[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [53]:
x_test

age  affordibility
9    61              1
25   54              1
8    62              1
21   26              0
0    22              1
12   27              0

In [54]:
prediction_fucntion(61 , 1)

/var/folders/fd/2d33_ptj5sndr1qwvq88fzc40000gn/T/ipykernel_90426/3885159617.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1 + math.exp(-x))


0.8497789566560162

# we can see the value using raw python and tensorflow method is same used python just for an understanding